### ISSUE TITLE
Gameplay programming

### ISSUE THREAD

**Issue by ivarhaugseth** [ivarhaugseth/BoomerShooter#1]
Player side gameplay programming.
 - Movement bindings
 - Action bindings

**Comment by ivarhaugseth** [comment]
So dash can only occur whilst player is moving. Can the dash go forward if the player is not moving?

**Comment by pettersandvik0** [comment]
> So dash can only occur whilst player is moving. Can the dash go forward if the player is not moving?

The dash is currently setup to use the players velocity for x and y and launches the player in a direction based on the velocity. So if the player is standing still and there is no velocity he can't dash. I would say that this is just a temporary version of the dash though and it will likely be tweaked. For example if we have an enemy that can knock back the player, pressing the dash button would make the player dash in the direction they were knocked back in which wouldn't really make sense.

Also i am aware of the bug/unintended feature where if you try to dash while stationary you are still technically dashing although you are not moving. So it activates the cooldown for the dashing. 

I likely won't tweak any of this before next week though.
